databases:
  - name: django-forum-db
    plan: Basic-256mb

services:
  - type: web
    name: django-forum
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Main.wsgi:application --bind 0.0.0.0:$PORT
    postDeployCommand: python manage.py migrate --noinput
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "1"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-forum-db
          property: connectionString


