databases:
  - name: django-forum-db
    plan: starter

services:
  - type: web
    name: django-forum
    env: python
    plan: starter
    buildCommand: python -m pip install --upgrade pip && python -m pip install "setuptools<70" wheel && python -m pip install --no-build-isolation -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn Main.wsgi:application --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - --log-level info --capture-output
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "1"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-forum-db
          property: connectionString





